_wandb:
    value:
        cli_version: 0.23.0
        e:
            96rbsa9j814rj830aaqh8vtiw3vcmy4a:
                args:
                    - headless=False
                    - task.env.objSet=ball
                    - task=AllegroArmMOAR
                    - task.env.axis=z
                    - task.env.numEnvs=8192
                    - train.params.config.minibatch_size=16384
                    - train.params.config.central_value_config.minibatch_size=16384
                    - task.env.observationType=full_stack_baoding
                    - task.env.legacy_obs=True
                    - task.env.ablation_mode=no-pc
                    - experiment=baoding
                    - train.params.config.user_prefix=baoding
                    - wandb_activate=True
                    - task.env.numEnvs=1024
                    - train.params.config.minibatch_size=4096
                    - train.params.config.central_value_config.minibatch_size=4096
                    - headless=True
                codePath: isaacgymenvs/train.py
                codePathLocal: isaacgymenvs/train.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "489997189120"
                        used: "75096489984"
                email: madhurthareja1105@gmail.com
                executable: /home/madhurthareja/miniconda3/envs/robosyn/bin/python
                git:
                    commit: 1e5cc92864b87fbe60482a923002b5499ec5e799
                    remote: https://github.com/YingYuan0414/in-hand-rotation.git
                gpu: NVIDIA GeForce RTX 3050
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2304
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3050
                      uuid: GPU-5e1ad103-17b7-fe71-9627-3830de8f8a9b
                host: ubuntu
                memory:
                    total: "16599109632"
                os: Linux-6.14.0-36-generic-x86_64-with-glibc2.17
                program: ./isaacgymenvs/train.py
                python: CPython 3.8.20
                root: /home/madhurthareja/itachicmd/in-hand-rotation
                startedAt: "2025-12-01T05:45:40.278924Z"
                writerId: 96rbsa9j814rj830aaqh8vtiw3vcmy4a
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 30
                - 50
                - 53
            "2":
                - 1
                - 5
                - 30
                - 50
                - 53
            "3":
                - 13
                - 16
                - 35
            "4": 3.8.20
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
capture_video:
    value: false
capture_video_freq:
    value: 1464
capture_video_len:
    value: 100
checkpoint:
    value: ""
experiment:
    value: baoding
force_render:
    value: true
graphics_device_id:
    value: 0
headless:
    value: true
max_iterations:
    value: ""
multi_gpu:
    value: false
num_envs:
    value: ""
num_subscenes:
    value: 4
num_threads:
    value: 4
physics_engine:
    value: physx
pipeline:
    value: gpu
player_action_savepath:
    value: ./a.pth
rl_device:
    value: cuda:0
seed:
    value: 42
sim_device:
    value: cuda:0
solver_type:
    value: 1
task:
    value:
        env:
            ablation_mode: no-pc
            actionPenaltyScale: 0
            actionsMovingAverage: 0.8
            aggregateMode: 1
            asset:
                assetFileName: urdf/xarm6/xarm6_allegro_left_fsr.urdf
                assetFileNameBlock: urdf/objects/cube_multicolor_allegro.urdf
                assetFileNameEgg: mjcf/open_ai_assets/hand/egg.xml
                assetFileNamePen: mjcf/open_ai_assets/hand/pen.xml
            asymmetric_observations: true
            aux_coef: 0
            axis: z
            camera:
                fov: 69.4
                height: 72
                pos:
                    - 0.45252319
                    - 0.33285737
                    - 0.5127288
                rot:
                    - -0.6354564
                    - 44.3181397
                    - -70.6868244
                width: 96
            clipActions: 1
            clipObservations: 5
            contact_coef: 0
            controlFrequencyInv: 6
            controlPenaltyScale: 0
            disableSet: 0
            distRewardScale: -3
            dofSpeedScale: 20
            enableDebugVis: false
            envSpacing: 0.75
            episodeLength: 500
            fallDistance: 0.1
            fallPenalty: -50
            finger_coef: 0.1
            force_debug: false
            forceDecay: 0.99
            forceDecayInterval: 0.1
            forceLimitScale: 1
            forceProbRange:
                - 0.2
                - 0.25
            forceProbScalar: 0.25
            forceScale: 2
            handInit: default
            is_distillation: false
            latency: 0.2
            legacy_obs: true
            m_low: 0.2
            m_up: 0.6
            main_coef: 0
            maxConsecutiveSuccesses: 0
            numEnvs: 1024
            numTestEnvs: 16
            objInit: new
            objSet: ball
            objectSize: large
            objectType: block
            obs_stack: 4
            observation:
                obs: null
                pointcloud:
                    bound:
                        - 0.5
                        - 10
                        - -1
                        - 1
                        - 0.12
                        - 0.8
                    numSample: 808
            observationType: full_stack_baoding
            pc_ablation: false
            pc_category: mug
            pc_mode: label
            printNumSuccesses: false
            reachGoalBonus: 250
            relScale: 0.2
            resetDofPosRandomInterval: 0.2
            resetDofVelRandomInterval: 0
            resetPositionNoise: 0.01
            resetRotationNoise: 0
            rewardType: finger
            robotStiffness: 3
            rotEps: 0.1
            rotRewardScale: 1
            sensor: thick
            sensorNoise: 0.1
            sensorThresh: 1
            skill_step: 500
            spin_coef: 1
            startPositionNoise: 0.01
            startRotationNoise: 0
            stiffnessScale: 1
            successTolerance: 0.1
            test:
                test_m_low: 0.1
                test_m_up: 1.4
            torque_coef: -0.0003
            useInitRandomRotation: false
            usePrevTarget: false
            useRelativeControl: true
            vel_coef: -0.1
            work_coef: -0.0003
        name: AllegroArmMOAR
        physics_engine: physx
        sim:
            dt: 0.01667
            gravity:
                - 0
                - 0
                - -9.81
            physx:
                bounce_threshold_velocity: 0.2
                contact_collection: 2
                contact_offset: 0.002
                default_buffer_size_multiplier: 5
                max_depenetration_velocity: 100
                max_gpu_contact_pairs: 8388608
                num_position_iterations: 8
                num_subscenes: 4
                num_threads: 4
                num_velocity_iterations: 0
                rest_offset: 0
                solver_type: 1
                use_gpu: true
            substeps: 2
            up_axis: z
            use_gpu_pipeline: true
        task:
            enableCameraSensors: false
            randomization_params:
                actions:
                    distribution: gaussian
                    operation: additive
                    range:
                        - 0
                        - 0.04
                    range_correlated:
                        - 0
                        - 0.015
                actor_params:
                    hand:
                        color: false
                        dof_properties:
                            lower:
                                distribution: gaussian
                                operation: additive
                                range:
                                    - 0
                                    - 1e-05
                            stiffness:
                                distribution: loguniform
                                operation: scaling
                                range:
                                    - 0.75
                                    - 1.5
                            upper:
                                distribution: gaussian
                                operation: additive
                                range:
                                    - 0
                                    - 1e-05
                frequency: 1000
                observations:
                    distribution: gaussian
                    operation: additive
                    range:
                        - 0
                        - 0.05
                    range_correlated:
                        - 0
                        - 0.001
                sim_params:
                    gravity:
                        distribution: gaussian
                        operation: additive
                        range:
                            - 0
                            - 0.3
            randomize: true
task_name:
    value: AllegroArmMOAR
test:
    value: false
torch_deterministic:
    value: false
train:
    value:
        params:
            algo:
                name: a2c_continuous
            config:
                auto_prefix: S1.0_C0.0_M0.0
                bc_loss_coef: 0.01
                bounds_loss_coef: 0.005
                bptt_len: 16
                central_value_config:
                    clip_value: true
                    kl_threshold: 0.016
                    learning_rate: 0.0005
                    lr_schedule: adaptive
                    mini_epochs: 4
                    minibatch_size: 4096
                    network:
                        central_value: true
                        mlp:
                            activation: elu
                            d2rl: false
                            initializer:
                                name: default
                            regularizer:
                                name: None
                            units:
                                - 512
                                - 512
                                - 256
                                - 256
                        name: actor_critic
                    normalize_input: true
                    schedule_type: standard
                    truncate_grads: true
                clip_value: true
                critic_coef: 5
                e_clip: 0.2
                entropy_coef: 0
                env_name: rlgpu
                gamma: 0.99
                grad_norm: 1
                horizon_length: 16
                kl_threshold: 0.02
                learning_rate: 0.0001
                lr_schedule: adaptive
                max_epochs: 20100
                mini_epochs: 4
                minibatch_size: 4096
                mixed_precision: false
                multi_gpu: false
                name: baoding
                normalize_advantage: true
                normalize_input: true
                normalize_value: true
                num_actors: 1024
                player:
                    desired_games: 10000
                    deterministic: true
                    games_num: 2
                    games_repeat: 1
                    print_stats: true
                player_collect: false
                ppo: true
                prefix: ""
                print_stats: true
                reward_shaper:
                    scale_value: 0.01
                save_best_after: 100
                save_frequency: 100
                schedule_type: standard
                score_to_win: 100000
                seq_length: 4
                tau: 0.95
                truncate_grads: Trues
                user_prefix: baoding
                value_bootstrap: true
                weight_decay: 0
            load_checkpoint: false
            load_path: ""
            model:
                name: continuous_a2c_logstd
            network:
                mlp:
                    activation: elu
                    d2rl: false
                    initializer:
                        name: default
                    regularizer:
                        name: None
                    units:
                        - 512
                        - 256
                        - 256
                name: actor_critic
                pointnet: small
                separate: false
                space:
                    continuous:
                        fixed_sigma: true
                        mu_activation: None
                        mu_init:
                            name: default
                        sigma_activation: None
                        sigma_init:
                            name: const_initializer
                            val: 0
            seed: 42
wandb_activate:
    value: true
wandb_entity:
    value: ""
wandb_group:
    value: ""
wandb_name:
    value: baoding
wandb_project:
    value: isaacgymenvs
